services:
  web:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "30534:8000"
    environment:
      - DEBUG=${DEBUG}
      - HUGGINGFACE_HUB_CACHE=.cache
    volumes:
      - .:/app
