name: Deploy Pipeline
on:
  push:
    branches:
      - "main"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/riccardoalv/vanda:main
            ghcr.io/riccardoalv/vanda:${{ github.sha }}

  deploy:
    runs-on: self-hosted
    needs:
      - build-and-push-image
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: create env file
        run: |
          echo "GIT_COMMIT_HASH=${{ github.sha }}" >> .env
          echo "EMAIL=${{ secrets.EMAIL }}" >> .env
          echo "FASTAPI_ROOT_PATH=${{ secrets.EMAIL }}" >> .env
          echo "DEBUG=0" >> .env

      - name: Docker Stack Deploy
        env:
          GIT_COMMIT_HASH: ${{ github.sha }}
        uses: kitconcept/docker-stack-deploy@v1.2.0
        with:
          stack_name: vanda
          registry: "ghcr.io"
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          stack_file: docker-stack.yml
          remote_private_key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
