name: Run Tests

on:
  push:
    branches:
      - dev
      - hml
  pull_request:
    branches:
      - dev
      - hml

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: "postgres:16-alpine"
        env:
          POSTGRES_USER: ${{ vars.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ vars.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ vars.POSTGRES_DB }}
        ports:
          - "5432:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
