name: Run Tests

on:
  push:
    branches:
      - dev
      - hml
  pull_request:
    branches:
      - dev
      - hml

jobs:
  run-tests:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install system dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y libpq-dev

      - name: Configure Pipenv to use Conda's Python
        run: |
          pip install --upgrade pip pipenv
          pipenv sync --dev

      - name: Run tests with pytest
        env:
          EMAIL: example@example.com
          DEBUG: 1
        run: |
          pipenv run pytest --maxfail=3 --disable-warnings
